import React from 'react';
import Seo from './Seo';
import { SITE, CONTACT } from './siteConfig';

export default function Terms() {
  return (
    <>
      <Seo
        title="Terms of Service | ROSKYRO"
        description="Terms of Service governing the use of ROSKYRO's website and AI growth technology services."
        path="/terms"
      />

      <section className="pt-32 pb-24 bg-slate-950 min-h-screen">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 space-y-6 text-slate-300 text-sm leading-relaxed font-sans">
          <h1 className="font-display text-3xl font-extrabold text-white mb-2">Terms of Service</h1>
          <p className="text-slate-500 text-xs font-mono">Last updated: June 2026</p>

          <p>
            These Terms of Service govern your use of {SITE.url} and any services provided by {SITE.name}. By
            using our website or engaging our services, you agree to these terms.
          </p>

          <h2 className="font-display text-xl font-bold text-white pt-4">Services</h2>
          <p>
            {SITE.name} provides AI-powered digital visibility, marketing technology, and automation services for
            small and medium businesses, including but not limited to Google Business Profile optimization, SEO,
            AEO, GEO, WhatsApp automation, and reputation management. Specific deliverables, timelines, and fees
            for any engagement are agreed separately in writing (including via WhatsApp or email) before work
            begins.
          </p>

          <h2 className="font-display text-xl font-bold text-white pt-4">Free Audit Tool</h2>
          <p>
            The instant estimate generated by our free audit tool on this website is a preliminary, illustrative
            estimate based on common patterns observed across similar unaudited businesses. It is not a
            substitute for the detailed, manual review our team conducts during an actual engagement, and actual
            findings may differ.
          </p>

          <h2 className="font-display text-xl font-bold text-white pt-4">Payments</h2>
          <p>
            Setup fees and recurring fees referenced on our Pricing page are indicative starting points. Final
            pricing for your specific business is confirmed in writing prior to commencement of work.
          </p>

          <h2 className="font-display text-xl font-bold text-white pt-4">No Guaranteed Outcomes</h2>
          <p>
            While we design our systems to maximize visibility and lead generation, we do not guarantee specific
            search rankings, AI citation placements, or revenue outcomes, as these depend on factors outside our
            control (including platform algorithm changes).
          </p>

          <h2 className="font-display text-xl font-bold text-white pt-4">Limitation of Liability</h2>
          <p>
            {SITE.name} shall not be liable for any indirect, incidental, or consequential damages arising from
            the use of our website or services, to the maximum extent permitted by applicable law.
          </p>

          <h2 className="font-display text-xl font-bold text-white pt-4">Contact</h2>
          <p>
            Questions about these terms can be sent to{' '}
            <a href={`mailto:${CONTACT.email}`} className="text-neon-cyan hover:underline">
              {CONTACT.email}
            </a>
            .
          </p>

          <p className="text-slate-500 text-xs pt-6 border-t border-slate-900">
            This is a general template and should be reviewed by a qualified legal professional before relying on
            it for your business.
          </p>
        </div>
      </section>
    </>
  );
}
